2022-07-30 14:10:46.5695                
 [INFO]  : ConnMultiplexer_ConnectionRestored:                 
  ConnectionMultiplexer.TryCompleteHandler => RedisHelper.ConnMultiplexer_ConnectionRestored => Logger.Process               
 ------------------------------------------------
2022-07-30 14:10:46.5714                
 [ERROR]  : ConnMultiplexer_ConnectionFailed: StackExchange.Redis.RedisConnectionException: SocketFailure (ReadSocketError/TimedOut, last-recv: 357) on 114.115.152.192:6379/Interactive, Idle/Faulted, last: INFO, origin: ReadFromPipe, outstanding: 1, last-read: 82s ago, last-write: 21s ago, unanswered-write: 21s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 9 of 10 available, in: 0, in-pipe: 0, out-pipe: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.5.43.42402 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode)
   在 Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult()
   在 Pipelines.Sockets.Unofficial.SocketConnection.<DoReceiveAsync>d__73.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   在 System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   在 System.IO.Pipelines.Pipe.GetReadAsyncResult()
   在 StackExchange.Redis.PhysicalConnection.<ReadFromPipe>d__115.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---                
  ConnectionMultiplexer.TryCompleteHandler => RedisHelper.ConnMultiplexer_ConnectionFailed => Logger.Process               
 ------------------------------------------------
2022-07-30 14:10:46.5714                
 [INFO]  : 配置更改:ConnMultiplexer_ConfigurationChanged: 114.115.152.192:6379                
  ConnectionMultiplexer.TryCompleteHandler => RedisHelper.ConnMultiplexer_ConfigurationChanged => Logger.Process               
 ------------------------------------------------
2022-07-30 17:43:05.4550                
 [ERROR]  : System.TypeInitializationException: “NanXingService_WMS.Utils.RabbitMQ.RabbitMQUtils”的类型初始值设定项引发异常。 ---> RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> System.AggregateException: 发生一个或多个错误。 ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 192.168.1.118:5672
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 RabbitMQ.Client.Impl.TcpClientAdapter.<ConnectAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 RabbitMQ.Client.Impl.TaskExtensions.<TimeoutAfter>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)
   --- 内部异常堆栈跟踪的结尾 ---
   在 RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)
   在 RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingAddressFamily(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout, AddressFamily family)
   在 RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)
   在 RabbitMQ.Client.ConnectionFactory.CreateFrameHandler(AmqpTcpEndpoint endpoint)
   在 RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   --- 内部异常堆栈跟踪的结尾 ---
   在 RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   在 RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)
   在 RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- 内部异常堆栈跟踪的结尾 ---
   在 RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   在 NanXingService_WMS.Utils.RabbitMQ.RabbitMQUtils.CreateConnection() 位置 D:\项目\南兴果仁\南兴果仁WMS智能仓储管理系统\NaXingService_WMS\Utils\RabbitMQ\RabbitMQUtils.cs:行号 54
   在 NanXingService_WMS.Utils.RabbitMQ.RabbitMQUtils..cctor() 位置 D:\项目\南兴果仁\南兴果仁WMS智能仓储管理系统\NaXingService_WMS\Utils\RabbitMQ\RabbitMQUtils.cs:行号 31
   --- 内部异常堆栈跟踪的结尾 ---
   在 NanXingService_WMS.Utils.RabbitMQ.RabbitMQUtils.Send[T](String queueName, List`1 obj)
   在 NanXingService_WMS.Services.ProPlanOrderManager.AddProOrders(List`1 list, Boolean changeCrm) 位置 D:\项目\南兴果仁\南兴果仁WMS智能仓储管理系统\NaXingService_WMS\Managers\ProPlanOrderManager.cs:行号 184                
  CRMApplyNew.Save => ProPlanOrderManager.AddProOrders => Logger.Process               
 ------------------------------------------------
2022-07-30 17:50:41.3803                
 [ERROR]  : ConnMultiplexer_ConnectionFailed: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, last-recv: 0) on 114.115.152.192:6379/Subscription, Idle/MarkProcessed, last: PING, origin: ReadFromPipe, outstanding: 0, last-read: 0s ago, last-write: 30s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 6 of 10 available, in: 0, in-pipe: 0, out-pipe: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.5.43.42402                
  ConnectionMultiplexer.TryCompleteHandler => RedisHelper.ConnMultiplexer_ConnectionFailed => Logger.Process               
 ------------------------------------------------
2022-07-30 17:50:41.3803                
 [ERROR]  : ConnMultiplexer_ConnectionFailed: StackExchange.Redis.RedisConnectionException: SocketClosed (ReadEndOfStream, last-recv: 0) on 114.115.152.192:6379/Interactive, Idle/MarkProcessed, last: INFO, origin: ReadFromPipe, outstanding: 0, last-read: 0s ago, last-write: 30s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 4 of 10 available, in: 0, in-pipe: 0, out-pipe: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.5.43.42402                
  ConnectionMultiplexer.TryCompleteHandler => RedisHelper.ConnMultiplexer_ConnectionFailed => Logger.Process               
 ------------------------------------------------
2022-07-30 17:50:43.9702                
 [INFO]  : 配置更改:ConnMultiplexer_ConfigurationChanged: 114.115.152.192:6379                
  ConnectionMultiplexer.TryCompleteHandler => RedisHelper.ConnMultiplexer_ConfigurationChanged => Logger.Process               
 ------------------------------------------------
2022-07-30 17:51:34.5969                
 [INFO]  : ConnMultiplexer_ConnectionRestored:                 
  ConnectionMultiplexer.TryCompleteHandler => RedisHelper.ConnMultiplexer_ConnectionRestored => Logger.Process               
 ------------------------------------------------
2022-07-30 17:51:34.6913                
 [INFO]  : 配置更改:ConnMultiplexer_ConfigurationChanged: 114.115.152.192:6379                
  ConnectionMultiplexer.TryCompleteHandler => RedisHelper.ConnMultiplexer_ConfigurationChanged => Logger.Process               
 ------------------------------------------------
2022-07-30 17:51:34.6913                
 [INFO]  : ConnMultiplexer_ConnectionRestored:                 
  ConnectionMultiplexer.TryCompleteHandler => RedisHelper.ConnMultiplexer_ConnectionRestored => Logger.Process               
 ------------------------------------------------
2022-07-30 18:08:22.8682                
 [ERROR]  : System.TypeInitializationException: “NanXingService_WMS.Utils.RabbitMQ.RabbitMQUtils”的类型初始值设定项引发异常。 ---> RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> System.AggregateException: 发生一个或多个错误。 ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 192.168.1.118:5672
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 RabbitMQ.Client.Impl.TcpClientAdapter.<ConnectAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 RabbitMQ.Client.Impl.TaskExtensions.<TimeoutAfter>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)
   --- 内部异常堆栈跟踪的结尾 ---
   在 RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)
   在 RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingAddressFamily(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout, AddressFamily family)
   在 RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)
   在 RabbitMQ.Client.ConnectionFactory.CreateFrameHandler(AmqpTcpEndpoint endpoint)
   在 RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   --- 内部异常堆栈跟踪的结尾 ---
   在 RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   在 RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)
   在 RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- 内部异常堆栈跟踪的结尾 ---
   在 RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   在 NanXingService_WMS.Utils.RabbitMQ.RabbitMQUtils.CreateConnection() 位置 D:\项目\南兴果仁\南兴果仁WMS智能仓储管理系统\NaXingService_WMS\Utils\RabbitMQ\RabbitMQUtils.cs:行号 54
   在 NanXingService_WMS.Utils.RabbitMQ.RabbitMQUtils..cctor() 位置 D:\项目\南兴果仁\南兴果仁WMS智能仓储管理系统\NaXingService_WMS\Utils\RabbitMQ\RabbitMQUtils.cs:行号 31
   --- 内部异常堆栈跟踪的结尾 ---
   在 NanXingService_WMS.Utils.RabbitMQ.RabbitMQUtils.Send[T](String queueName, List`1 obj)
   在 NanXingService_WMS.Services.ProPlanOrderManager.AddProOrders(List`1 list, Boolean changeCrm) 位置 D:\项目\南兴果仁\南兴果仁WMS智能仓储管理系统\NaXingService_WMS\Managers\ProPlanOrderManager.cs:行号 184                
  CRMApplyNew.Save => ProPlanOrderManager.AddProOrders => Logger.Process               
 ------------------------------------------------
2022-07-30 18:13:47.5389                
 [INFO]  :  --成功发送到broker服务器CRMPushPlan--                 
  ModelBase.HandleBasicAck => <>c__DisplayClass8_0.<CreateWorkQueue>b__1 => Logger.Process               
 ------------------------------------------------
2022-07-30 18:14:34.6793                
 [ERROR]  : ConnMultiplexer_ConnectionFailed: StackExchange.Redis.RedisConnectionException: SocketFailure (ReadSocketError/TimedOut, last-recv: 56) on 114.115.152.192:6379/Subscription, Idle/Faulted, last: PING, origin: ReadFromPipe, outstanding: 1, last-read: 79s ago, last-write: 19s ago, unanswered-write: 19s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 9 of 10 available, in: 0, in-pipe: 0, out-pipe: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.5.43.42402 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode)
   在 Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult()
   在 Pipelines.Sockets.Unofficial.SocketConnection.<DoReceiveAsync>d__73.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   在 System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   在 System.IO.Pipelines.Pipe.GetReadAsyncResult()
   在 StackExchange.Redis.PhysicalConnection.<ReadFromPipe>d__115.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---                
  ConnectionMultiplexer.TryCompleteHandler => RedisHelper.ConnMultiplexer_ConnectionFailed => Logger.Process               
 ------------------------------------------------
2022-07-30 18:14:34.7276                
 [INFO]  : 配置更改:ConnMultiplexer_ConfigurationChanged: 114.115.152.192:6379                
  ConnectionMultiplexer.TryCompleteHandler => RedisHelper.ConnMultiplexer_ConfigurationChanged => Logger.Process               
 ------------------------------------------------
2022-07-30 18:14:34.7635                
 [INFO]  : ConnMultiplexer_ConnectionRestored:                 
  ConnectionMultiplexer.TryCompleteHandler => RedisHelper.ConnMultiplexer_ConnectionRestored => Logger.Process               
 ------------------------------------------------
2022-07-30 18:14:34.8284                
 [INFO]  : 配置更改:ConnMultiplexer_ConfigurationChanged: 114.115.152.192:6379                
  ConnectionMultiplexer.TryCompleteHandler => RedisHelper.ConnMultiplexer_ConfigurationChanged => Logger.Process               
 ------------------------------------------------
2022-07-30 18:18:59.5923                
 [INFO]  :  --成功发送到broker服务器CRMPushPlan--                 
  ModelBase.HandleBasicAck => <>c__DisplayClass8_0.<CreateWorkQueue>b__1 => Logger.Process               
 ------------------------------------------------
2022-07-30 18:23:59.4310                
 [DEBUG]  : ID：82:S20220730002                
  PlanToProConfirm.btnSubmit_Click => ProductOrderManager.PushToProOrder => Logger.Process               
 ------------------------------------------------
2022-07-30 18:23:59.4831                
 [INFO]  :  --成功发送到broker服务器CRMPushPro--                 
  ModelBase.HandleBasicAck => <>c__DisplayClass8_0.<CreateWorkQueue>b__1 => Logger.Process               
 ------------------------------------------------
